### ISSUE TITLE
Traffic-data endpoint no longer exists 

### ISSUE THREAD

**Issue by dtolb** [kdzwinel/AllGitHubTraffic#1]
Github seems to have deprecated the traffic-data endpoint

**Comment by kdzwinel** [comment]
Traffic-data endpoint never existed ;) They were sending traffic data over ajax, but it was an internal call. I hijacked it. Anyway, this extension is simple enough, I'll have a quick look in a sec.

**Comment by dtolb** [comment]
Yeah I just saw that, was trying to get it working. Not sure if the new UI broke the extension, been mucking around with it and had to hardcode the name

**Comment by kdzwinel** [comment]
it probably did, haven't thought of that. Name was pulled from the website DOM. I'll take a look and report back in 1h

**Comment by kdzwinel** [comment]
I was managed to fix the user login issue, but fetching data got harder - github tightened security on their cookies. Not sure if I can work around this.

**Comment by dtolb** [comment]
No worries! Thanks for looking in to the bugs. I was trying to measure the traffic across all our repos and came across your extension. I may just use ZombieJS or something to pull the information.

**Comment by kdzwinel** [comment]
I've managed to fix it - it was a matter of using `fetch` with `mode:cors` instead of a "classic" XMLHttpRequest.

If you've installed it via webstore it should autoupdate to v0.13 in ~1h.

**Comment by dtolb** [comment]
:+1: awesome !
